name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build devcontainer image (load locally)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          tags: "local/parallelmind-dev:latest"
          push: false
          load: true
          build-args: |
            INSTALL_PY_DEPS=0

      - name: Configure and build in devcontainer image
        run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace \
            local/parallelmind-dev:latest \
            bash -lc "cmake --version && mkdir -p build && cd build && cmake .. && make -j"

      - name: Run unit tests (exclude dataset-dependent tests)
        run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace/build \
            local/parallelmind-dev:latest \
            bash -lc "ctest --version && ctest --output-on-failure -E test_npy_reader"
